FROM karalabe/xgo-latest AS build
ARG VERSION=release-v0.32

WORKDIR ${GOPATH}/src/github.com/google
RUN git clone --branch ${VERSION} https://github.com/google/cadvisor.git
WORKDIR ${GOPATH}/src/github.com/google/cadvisor
RUN xgo --targets=linux/arm-7 .

FROM alpine

COPY --from=build /build /build
